In [1]:
import numpy as np

## 数组运算
- 标量(Scalar): 只有大小，没有法相的量。如1，2，3等。
- 向量(Vector): 也叫矢量，有大小和方向的量，其实就是一串数字，如(1,2)
- 矩阵(Matrix): 好几个向量拍成一排合并成的一堆数字
- 张量(Tensor): 按照任意维排列的一堆数字的推广。标量是零维张量，向量是一维张量，矩阵是二维张量

### 数组与标量之间的运算

In [9]:
data1 = np.arange(10).reshape(2,5)
data2 = 10
print('data1: \n', data1)
print('data2: ', data2)

print('data1+data2: \n', data1+data2)
print('data1-data2: \n', data1-data2)
print('data1*data2: \n', data1*data2)
print('data1/data2: \n', data1/data2)

data1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
data2:  10
data1+data2: 
 [[10 11 12 13 14]
 [15 16 17 18 19]]
data1-data2: 
 [[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]]
data1*data2: 
 [[ 0 10 20 30 40]
 [50 60 70 80 90]]
data1/data2: 
 [[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]


### 向量化运算

In [12]:
data1 = np.arange(10).reshape(2, 5)
data2 = np.arange(10).reshape(2, 5)

print('data1+data2: \n', data1+data2)
print('data1-data2: \n', data1-data2)
print('data1*data2: \n', data1*data2)
print('data1/data2: \n', data1/data2)

data1+data2: 
 [[ 0  2  4  6  8]
 [10 12 14 16 18]]
data1-data2: 
 [[0 0 0 0 0]
 [0 0 0 0 0]]
data1*data2: 
 [[ 0  1  4  9 16]
 [25 36 49 64 81]]
data1/data2: 
 [[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in true_divide
  import sys


### 数组广播
TODO: 待补充

## 常用函数

In [28]:
data1 = np.array([1,4,9,16,25,36]).reshape(2,3)
print('data1: \n', data1)
print('sqrt: \n', np.sqrt(data1)) # 开发
print('abs: \n', np.abs(data1)) # 绝对值
print('square: \n', np.square(data1)) # 求平方

data2 = np.array([1,2,3,4,5,6]).reshape(2,3)
print('data2: \n', data2)
print('data1+data2: \n', np.add(data1, data2)) # 两个矩阵相加
print('data1*data2: \n', np.multiply(data1, data2)) # 两个矩阵相乘
print('greater: \n', np.greater(data1, data2)) # 元素比较

data1: 
 [[ 1  4  9]
 [16 25 36]]
sqrt: 
 [[1. 2. 3.]
 [4. 5. 6.]]
abs: 
 [[ 1  4  9]
 [16 25 36]]
square: 
 [[   1   16   81]
 [ 256  625 1296]]
data2: 
 [[1 2 3]
 [4 5 6]]
data1+data2: 
 [[ 2  6 12]
 [20 30 42]]
data1*data2: 
 [[  1   8  27]
 [ 64 125 216]]
greater: 
 [[False  True  True]
 [ True  True  True]]


## 数据统计

In [41]:
data = np.arange(2, 20)
print('data: \n', data)

print('sum: ', data.sum())
print('mean: ', data.mean())
print('min: ', data.min())
print('max: ', data.max())
print('argmin: ', data.argmin())
print('argmax: ', data.argmax())
print('cumsum: ', data.cumsum()) # 元素累加
print('cumprod: ', data.cumprod()) # 元素累计积

data: 
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
sum:  189
mean:  10.5
min:  2
max:  19
argmin:  0
argmax:  17
cumsum:  [  2   5   9  14  20  27  35  44  54  65  77  90 104 119 135 152 170 189]
cumprod:  [                 2                  6                 24
                120                720               5040
              40320             362880            3628800
           39916800          479001600         6227020800
        87178291200      1307674368000     20922789888000
    355687428096000   6402373705728000 121645100408832000]


## 随机数

In [43]:
np.random.rand(3,3)

array([[0.0472813 , 0.6490086 , 0.56793693],
       [0.82043207, 0.90965159, 0.76944866],
       [0.83052783, 0.71636763, 0.13288392]])

In [44]:
# 为
np.random.seed(0)
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])