## numpy 简述
Numpy(Numeric Python)提高了许多高级的数值编程工具，如：矩阵数据类型、矢量处理、以及精密的运算库。

1. python内置的list是无类型的；
2. 如需使用有类型的数组可以使用array.array；
3. numpy里有array更高效。

参考
- [Numpy简易入门](https://mp.weixin.qq.com/s/66SLsOBhUMP7qEuPE-BUnw)
- [Numpy练习题100题](https://github.com/rougier/numpy-100)


In [1]:
import numpy as np


In [2]:
array = np.array(np.arange(10))
print('array: ', array)
print('array type: ', type(array))
print('array dtype: ', array.dtype)
print('array ndim: ', array.ndim) # 维度
print('array size: ', array.size) # 数组元素的个数
print('array shape: ', array.shape)
print('array reshape[5, 2]: \n', array.reshape(2, 5))

array:  [0 1 2 3 4 5 6 7 8 9]
array type:  <class 'numpy.ndarray'>
array dtype:  int64
array ndim:  1
array size:  10
array shape:  (10,)
array reshape[5, 2]: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## 创建Numpy数组
### 创建一维数组

In [3]:
a = np.array([2,23,4,6,8,7], dtype=np.int32)  # 数据初始化array,可声明dtype的类型，常用int,float
a

array([ 2, 23,  4,  6,  8,  7], dtype=int32)

### 创建二维数组(矩阵)

In [4]:
aa = np.array([[2,23,4], [3,4,5]])
aa

array([[ 2, 23,  4],
       [ 3,  4,  5]])

In [5]:
# 将一维数组改成二维数组。2*3=6，如果数量不等于6就会报错。
a.reshape(2, 3)

array([[ 2, 23,  4],
       [ 6,  8,  7]], dtype=int32)

### 创建特定数组

In [10]:
# 生成连续数值数组,这里支持浮点类型(左闭右开)。而python里不支持浮点.
# 起始点，终点，步长
np.arange(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [11]:
# 和arrage类似，只是这里不是设置步长。
# 起始点，终点，分割份数；包括终点
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [6]:
# 创建全0的数组
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# 创建全1的数组
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# 创建全空数组，里面的值接近于零
np.empty((2,5))

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323]])

In [9]:
# 3*5的矩阵填充666
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [36]:
# 以2为底，指数为1,2...,10
np.logspace(1,10,10, base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [37]:
# 创建对角数组
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
# 主对角线偏移1的数组
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### 随机数

In [13]:
# 整数随机
np.random.randint(0,10, size=20)

array([4, 9, 7, 4, 8, 0, 8, 2, 5, 4, 0, 9, 4, 5, 2, 0, 8, 0, 0, 5])

In [14]:
# 0-1的随机数
np.random.random((2,5))

array([[0.60157761, 0.27184132, 0.68705957, 0.99141909, 0.83905959],
       [0.17041627, 0.03836569, 0.35918367, 0.59112083, 0.51972171]])

In [15]:
# 正态分布
np.random.normal(0,1,20)

array([-0.01312413,  1.08440394, -0.40227356, -2.56720585,  0.53032358,
       -1.00033302,  0.61709809,  0.68351382, -1.04925363, -1.0381731 ,
       -0.84274877, -0.51597932, -0.80671028, -1.33959063,  0.02002608,
       -0.6737917 ,  1.15690536, -0.11242984,  1.36617105,  0.73367844])

In [16]:
# 伪随机数(计算机里都是伪随机数)
np.random.seed(0) # 随机种子
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

## tile函数
找到矩阵的最小单位，然后title使用最小单位组织成目标矩阵。

In [17]:
# 一维：将[0,1]横向复制5次
np.tile([0,1], 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [18]:
# 二维：构建8*8棋盘。棋盘的最小单位是2*2矩阵[[1,0],[0,1]]，将其复制按照行和列分别复制4次即可(1代表黑格，0代表白格)
np.tile([[1,0],[0,1]], [4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## 数据类型与转化

In [19]:
data = np.array([[1,2,3],[4,5,6]])
data.dtype

dtype('int64')

In [20]:
data.astype('float64').dtype

dtype('float64')

In [21]:
data.astype(np.float64).dtype

dtype('float64')

## 索引和切片
### 普通索引与切片

In [22]:
# 一维数组索引
data = np.arange(10)
print(u'一维数组******')
print(u'data: ', data)
print(u'索引2对应的元素: ', data[2])
print(u'索引2~5对应的元素: ', data[2:5])
print(u'索引2~8,步长为2对应的元素: ', data[2:8:2])

# 二维数组索引
data = np.arange(25).reshape(5,5)
print(u'\n二维数组******')
print(u'data: \n', data)
print(u'data[2,1]: ', data[2,1])
print(u'data[2:]: \n', data[2:])
print(u'data[2,:]: \n', data[2,:])
print(u'data[2][0:3]: \n', data[2][0:3])

一维数组******
data:  [0 1 2 3 4 5 6 7 8 9]
索引2对应的元素:  2
索引2~5对应的元素:  [2 3 4]
索引2~8,步长为2对应的元素:  [2 4 6]

二维数组******
data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,1]:  11
data[2:]: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,:]: 
 [10 11 12 13 14]
data[2][0:3]: 
 [10 11 12]


### 花式索引

In [40]:
data = np.arange(25).reshape(5,5)
# 设置数组是只读
data.flags.writeable = False
print(u'data: \n', data)
print(u'data[[0,2]]: \n', data[[0,2]])  # 第0,2行
print(u'data[:][1]: \n', data[[1],[1]]) # 第1行第1列

data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[[0,2]]: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]
data[:][1]: 
 [6]


### 布尔型
支持布尔型按照条件筛选

In [48]:
data = np.arange(1, 26).reshape(5,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
# 筛选15~20之间的数据
data[(data>=15) & (data<=20)]

array([15, 16, 17, 18, 19, 20])

### 查找第n个元素对应的位置

In [25]:
# 查找6*7*8的数组，第100个元素对应的位置，默认是按行查找
np.unravel_index(100, (6,7,8), order='C')

(1, 5, 4)

In [26]:
# 按照列查找
np.unravel_index(100, (6,7,8), order='F')

(4, 2, 2)

## 合并与分割

### 合并

In [27]:
# 一维数组合并
data1 = np.array([0,1,2,3,4])
data2 = np.array([5,6,7,8,9])
np.concatenate([data1, data2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 二维数组合并 numpy.concatenate((a1, a2, ...), axis=0, out=None).axis=0为行，axis=1为列。
data1 = np.arange(0,6).reshape(2,3)
data2 = np.arange(10,16).reshape(2,3)

np.concatenate([data1, data2], axis=0)
np.concatenate([data1, data2], axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

## 分割

In [29]:
data = np.arange(0,25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
# 按行分割
upper, lower = np.vsplit(data, [2])
print('upper: \n', upper)
print('lower: \n', lower)

upper: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
lower: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
# 按列分割
left, right = np.hsplit(data, [2])
print('left: \n', left)
print('right: \n', right)

left: 
 [[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
right: 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


## 其他

### 逆序

In [32]:
data = np.arange(10)
reverse_data = data[::-1]
print('data: \n', data)
print('reverse_data: \n', reverse_data)

data: 
 [0 1 2 3 4 5 6 7 8 9]
reverse_data: 
 [9 8 7 6 5 4 3 2 1 0]


### 排序

### 转置

### 对角线

In [33]:
data = np.arange(9).reshape(3,3)
print('data: \n', data)

print(u'对角线 \n', np.diag(data))
print(u'对角线之上1个单位的元素 \n', np.diag(data, k=1))
print(u'对角线之下1个单位的元素 \n', np.diag(data, k=-1))

data: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
对角线 
 [0 4 8]
对角线之上1个单位的元素 
 [1 5]
对角线之下1个单位的元素 
 [3 7]


## 多种取整方式

In [34]:
data = np.random.uniform(-10,10,10)
print('data: \n', data)
print(u'截取整数部分: ', np.trunc(data))
print(u'向上取整: ', np.ceil(data))
print(u'向下取整: ', np.floor(data))
print(u'四舍五入取整: ', np.rint(data))

data: 
 [-2.33116962  5.83450076  0.5778984   1.36089122  8.51193277 -8.57927884
 -8.25741401 -9.59563205  6.65239691  5.56313502]
截取整数部分:  [-2.  5.  0.  1.  8. -8. -8. -9.  6.  5.]
向上取整:  [-2.  6.  1.  2.  9. -8. -8. -9.  7.  6.]
向下取整:  [ -3.   5.   0.   1.   8.  -9.  -9. -10.   6.   5.]
四舍五入取整:  [ -2.   6.   1.   1.   9.  -9.  -8. -10.   7.   6.]
