## numpy 简述
Numpy(Numeric Python)提高了许多高级的数值编程工具，如：矩阵数据类型、矢量处理、以及精密的运算库。

1. python内置的list是无类型的；
2. 如需使用有类型的数组可以使用array.array；
3. numpy里有array更高效。

参考
- [Numpy简易入门](https://mp.weixin.qq.com/s/66SLsOBhUMP7qEuPE-BUnw)
- [Numpy练习题100题](https://github.com/rougier/numpy-100)


In [1]:
import numpy as np


In [2]:
array = np.array(np.arange(10))
print('array: ', array)
print('array type: ', type(array))
print('array dtype: ', array.dtype)
print('array ndim: ', array.ndim) # 维度
print('array size: ', array.size) # 数组元素的个数
print('array shape: ', array.shape)
print('array reshape[5, 2]: \n', array.reshape(2, 5))

array:  [0 1 2 3 4 5 6 7 8 9]
array type:  <class 'numpy.ndarray'>
array dtype:  int64
array ndim:  1
array size:  10
array shape:  (10,)
array reshape[5, 2]: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## 创建Numpy数组
### 创建一维数组

In [3]:
a = np.array([2,23,4,6,8,7], dtype=np.int32)  # 数据初始化array,可声明dtype的类型，常用int,float
a

array([ 2, 23,  4,  6,  8,  7], dtype=int32)

### 创建二维数组(矩阵)

In [4]:
aa = np.array([[2,23,4], [3,4,5]])
aa

array([[ 2, 23,  4],
       [ 3,  4,  5]])

In [5]:
# 将一维数组改成二维数组
a.reshape(2, 3)

array([[ 2, 23,  4],
       [ 6,  8,  7]], dtype=int32)

### 创建特定数组

In [6]:
# 创建全0的数组
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# 创建全1的数组
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# 创建全空数组，里面的值接近于零
np.empty((2,5))

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323, 4.4e-323]])

In [18]:
# 生成连续数值数组,这里支持浮点类型(左闭右开)。而python里不支持浮点.
np.arange(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## 数据类型与转化

In [21]:
data = np.array([[1,2,3],[4,5,6]])
data.dtype

dtype('int64')

In [25]:
data.astype('float64').dtype

dtype('float64')

In [28]:
data.astype(np.float64).dtype

dtype('float64')

## 索引和切片
### 普通索引与切片

In [53]:
# 一维数组索引
data = np.arange(10)
print(u'一维数组******')
print(u'data: ', data)
print(u'索引2对应的元素: ', data[2])
print(u'索引2~5对应的元素: ', data[2:5])
print(u'索引2~8,步长为2对应的元素: ', data[2:8:2])

# 二维数组索引
data = np.arange(25).reshape(5,5)
print(u'\n二维数组******')
print(u'data: \n', data)
print(u'data[2,1]: ', data[2,1])
print(u'data[2:]: \n', data[2:])
print(u'data[2,:]: \n', data[2,:])
print(u'data[2][0:3]: \n', data[2][0:3])

一维数组******
data:  [0 1 2 3 4 5 6 7 8 9]
索引2对应的元素:  2
索引2~5对应的元素:  [2 3 4]
索引2~8,步长为2对应的元素:  [2 4 6]

二维数组******
data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,1]:  11
data[2:]: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,:]: 
 [10 11 12 13 14]
data[2][0:3]: 
 [10 11 12]


### 花式索引

In [70]:
data = np.arange(25).reshape(5,5)
print(u'data: \n', data)
print(u'data[[0,2]]: \n', data[[0,2]])  # 第0,2行
print(u'data[:][1]: \n', data[[1],[1]]) # 第1行第1列

data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[[0,2]]: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]
data[:][1]: 
 [6]


### 布尔型

In [ ]:
# 待补充