In [1]:
import numpy as np

## 查看版本信息

In [2]:
print(u'numpy 版本', np.__version__)
print(u'numpy 配置: \n', np.show_config()) 

numpy 版本 1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
numpy 配置: 
 None


## 数组内存占用

In [3]:
# 计算数组所在内存大小
data = np.arange(50000000)
%time print(u'数组所在内存大小: ', data.nbytes)
%time print(u'数组所在内存大小: ', data.size*data.itemsize)
# 也可以使用python内置的方法，不过效率估计会低一些
from sys import getsizeof
%time print(u'数组所在内存大小: ', getsizeof(data))

数组所在内存大小:  400000000
CPU times: user 167 µs, sys: 70 µs, total: 237 µs
Wall time: 200 µs
数组所在内存大小:  400000000
CPU times: user 668 µs, sys: 280 µs, total: 948 µs
Wall time: 1.08 ms
数组所在内存大小:  400000096
CPU times: user 52 µs, sys: 33 µs, total: 85 µs
Wall time: 73 µs


## 查看命令行帮助文档

In [4]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [5]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

## 忽略警告

In [6]:
default = np.seterr(all='ignore')
np.ones(1) / 0

array([inf])

## 打印设置

### threshold

In [11]:
data = np.arange(100)
print('data: \n', data)
# set_printoptions设置打印的属性。threshold代表元素超过多少后，缩略打印. 默认值1000
np.set_printoptions(threshold=10)
print('data: \n', data)
# 放开threshold，打印全部，不管数组多大
np.set_printoptions(threshold=np.inf)
print('data: \n', data)

data: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
data: 
 [ 0  1  2 ... 97 98 99]
data: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### precision
小数保留的位数

In [16]:
data = np.random.random(10)
print('data: \n', data)
np.set_printoptions(precision=2)
print('data: \n', data)

data: 
 [0.5728 0.1617 0.186  0.4077 0.1178 0.9409 0.2288 0.6876 0.5579 0.5325]
data: 
 [0.57 0.16 0.19 0.41 0.12 0.94 0.23 0.69 0.56 0.53]
