- 题目来源于：https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_no_solution.ipynb
- 参考：https://www.jianshu.com/p/385d47d03cfb

## 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

# 2.  Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.17.3'

In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


## 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. How to find the memory size of any array (★☆☆)

In [5]:
data = np.arange(50000000)
%time print(u'方法一: ', data.nbytes)
%time print(u'方法二: ', data.size*data.itemsize)
# 也可以使用python内置的方法，不过效率估计会低一些
from sys import getsizeof
%time print(u'方法三: ', getsizeof(data))

方法一:  400000000
CPU times: user 140 µs, sys: 62 µs, total: 202 µs
Wall time: 174 µs
方法二:  400000000
CPU times: user 1.05 ms, sys: 250 µs, total: 1.3 ms
Wall time: 12.7 ms
方法三:  400000096
CPU times: user 906 µs, sys: 255 µs, total: 1.16 ms
Wall time: 1.24 ms


## 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# 法一：
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [7]:
# 法二：
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
data = np.zeros(10)
data[4]=1
print('data: ', data)

data:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
data = np.arange(10, 50)
print('data: ', data)

data:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
data = np.arange(10, 50)
data = data[::-1]
print('data: ', data)

data:  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
data = np.arange(9).reshape(3,3)
print('data: \n', data)

data: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
data = np.array([1,2,0,0,4,0])
%time print(u'法一: ', np.nonzero(data))
# 使用bool索引
%time print(u'法二: ', data[data!=0])

法一:  (array([0, 1, 4]),)
CPU times: user 1.22 ms, sys: 1.19 ms, total: 2.42 ms
Wall time: 2.22 ms
法二:  [1 2 4]
CPU times: user 311 µs, sys: 29 µs, total: 340 µs
Wall time: 347 µs


## 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
# 创建一个3*3的单位矩阵
data = np.eye(3)
print('data: \n', data)

data: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
data = np.random.random([3,3,3])
print('data: \n', data)

data: 
 [[[0.86396051 0.51493416 0.97664101]
  [0.06076924 0.26678024 0.95968529]
  [0.58406754 0.88251217 0.6954239 ]]

 [[0.48268249 0.3956023  0.42667154]
  [0.01172937 0.53236197 0.88755348]
  [0.65828209 0.31440069 0.24254731]]

 [[0.15003678 0.06697021 0.51521561]
  [0.46564638 0.37462341 0.15107912]
  [0.31655866 0.64203346 0.73454666]]]


## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
data = np.random.random([10,10])
print(u'方法一:')
print('min: ', np.min(data))
print('max: ', np.max(data))

print(u'方法二:')
print('min: ', data.min())
print('max: ', data.max())

方法一:
min:  0.0022402034161036477
max:  0.9968891894511578
方法二:
min:  0.0022402034161036477
max:  0.9968891894511578


## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
data = np.random.random(30)
print('mean: ', data.mean())

mean:  0.5276073844523671


## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
# 创建二维数组，边界元素为1，内部元素为0
data = np.zeros([5,5])
data[[0,-1]]=1
data[:,[0,-1]]=1
print('方法一: \n', data)


data = np.ones([5,5])
data[1:-1, 1:-1]=0
print('方法二: \n', data)

方法一: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
方法二: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
# 在已有数组边上添加0
data = np.arange(1, 26).reshape(5,5)
data = np.pad(data, pad_width=1, mode='constant', constant_values=0)
print('data: \n', data)

data: 
 [[ 0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  0]
 [ 0  6  7  8  9 10  0]
 [ 0 11 12 13 14 15  0]
 [ 0 16 17 18 19 20  0]
 [ 0 21 22 23 24 25  0]
 [ 0  0  0  0  0  0  0]]


## 17. What is the result of the following expression? (★☆☆)

``` python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print('0 * np.nan: ', 0 * np.nan)
print('np.nan * np.nan: ', np.nan * np.nan)
print('np.nan - np.nan: ', np.nan - np.nan) # 两个空值相减为null
print('np.nan == np.nan: ', np.nan == np.nan) # null与null不能做等值判断，为false
print('np.nan > np.nan: ', np.nan > np.nan)
print('np.nan in set([np.nan]): ', np.nan in set([np.nan])) # 判断空值是否在数组里

0 * np.nan:  nan
np.nan * np.nan:  nan
np.nan - np.nan:  nan
np.nan == np.nan:  False
np.nan > np.nan:  False
np.nan in set([np.nan]):  True


## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
# 生成5*5的矩阵，在对角线下一个单位插入1,2,3,4
data = np.diag(1+np.arange(4),k=-1)
print(data)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
# 生成一个8*8的数组，如西洋棋一样纵横交错。
data = np.zeros([8,8], dtype=int)
data[::2,::2] = 1
data[1::2, 1::2] = 1
print('data: \n', data)

data: 
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
data = np.ones([6,7,8], dtype=int)

# 方法一：
x = int(100 / (7 * 8))
y = int((100 % (7 * 8)) / 8)
z = 100 % 8
print(u'方法一，x,y,z:', x, y, z)

# 方法二：使用numpy自带的函数
print(u'方法二，x,y,z:', np.unravel_index(100, (6,7,8)))

方法一，x,y,z: 1 5 4
方法二，x,y,z: (1, 5, 4)


## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
# 使用title函数创建8*8的棋盘。最小的组成单位是个2*2的矩阵[[1,0],[0,1]]。
np.tile([[1,0],[0,1]], [4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

## 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
# 归一化5*5矩阵
data = np.random.random((5,5))
print(u'归一化前: \n', data)
data = (data - np.mean(data)) / (np.std(data))
print(u'归一化后: \n', data)

归一化前: 
 [[0.28953191 0.32959012 0.81169812 0.65057045 0.63290608]
 [0.67134068 0.32123485 0.31199488 0.62150244 0.2825939 ]
 [0.75868379 0.52897088 0.40861597 0.69240574 0.82686651]
 [0.86926001 0.01556707 0.8249859  0.27522829 0.59894836]
 [0.36113315 0.75675193 0.15713638 0.17895353 0.31161895]]
归一化后: 
 [[-0.86665271 -0.70132925  1.28836959  0.62338264  0.55048035]
 [ 0.70910305 -0.73581211 -0.77394621  0.50341659 -0.89528646]
 [ 1.06957517  0.12153133 -0.37518316  0.79604027  1.35097077]
 [ 1.52593217 -1.99732785  1.34320934 -0.92568494  0.41033407]
 [-0.57114861  1.0616022  -1.41305982 -1.32301869 -0.77549772]]


## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
# 自定义dtype
rgba = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
rgba

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
# 两个矩阵的积

data1 = np.arange(15).reshape(5,3)
data2 = np.arange(6).reshape(3,2)
print('data1: \n', data1)
print('data2: \n', data2)
print('dot: \n', np.dot(data1, data2))

data1: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
data2: 
 [[0 1]
 [2 3]
 [4 5]]
dot: 
 [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
# 对于一维数组，将其中3~8的数替换为对应的负数
data = np.arange(20)
data[(data>3) & (data<8)] = data[(data>3) & (data<8)] * -1
print(u'法一: \n', data)

data = np.arange(20)
data[(data>3) & (data<8)] *= -1
print(u'法二: \n', data)

法一: 
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]
法二: 
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


## 26. What is the output of the following script? (★☆☆)

``` python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
# python内置的sum。 0+1+2+3+4-1=9
print(sum(range(5),-1))
# np.sum的第二个参数axis(维度)
print(np.sum(range(5),-1))

9
10


## 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

``` python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
# 考虑以下向量计算那个是合法的。
# 第一个z的乘积
z = np.arange(4).reshape(2,2)
print('z: \n', z)
print('z**z: \n', z**z)

z: 
 [[0 1]
 [2 3]]
z**z: 
 [[ 1  1]
 [ 4 27]]


## 28. What are the result of the following expressions?

``` python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print('np.array(0) / np.array(0): ', np.array(0) / np.array(0))
print('np.array(0) // np.array(0): ', np.array(0) // np.array(0))
print('np.array([np.nan]).astype(int).astype(float): ', np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0):  nan
np.array(0) // np.array(0):  0
np.array([np.nan]).astype(int).astype(float):  [-9.22337204e+18]


/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29. How to round away from zero a float array ? (★☆☆)

In [31]:
# 让float数组原理0
data = np.random.uniform(-10,+10,10)
print('data: \n', data)
print(u'处理后: \n', np.copysign(np.ceil(np.abs(data)), data))

data: 
 [ 7.99838071  3.21510688  3.06299664  2.91779129  5.07343519  1.06385543
 -5.04195436 -1.58637827  5.60199717 -0.24486241]
处理后: 
 [ 8.  4.  4.  3.  6.  2. -6. -2.  6. -1.]


## 30. How to find common values between two arrays? (★☆☆)

In [32]:
# 查找两个数组相同的元素
data1 = np.arange(25).reshape(5,5)
data2 = np.arange(2,18).reshape(4,4)

np.intersect1d(data1, data2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

## 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
# 忽略numpy所有警告
default = np.seterr(all='ignore')
np.ones(1) / 0
_ = np.seterr(**default)

## 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)


In [34]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

## 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
print('today: ', np.datetime64('today', 'D'))
print('yesterday: ', np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print('tomorrow: ', np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

today:  2019-11-24
yesterday:  2019-11-23
tomorrow:  2019-11-25


## 34. How to get all the dates corresponding to the month of July 2016? (★★☆)¶

In [36]:
# 得到7月所有的日期
np.arange('2019-07', '2019-08', dtype='datetime64[D]')

array(['2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04',
       '2019-07-05', '2019-07-06', '2019-07-07', '2019-07-08',
       '2019-07-09', '2019-07-10', '2019-07-11', '2019-07-12',
       '2019-07-13', '2019-07-14', '2019-07-15', '2019-07-16',
       '2019-07-17', '2019-07-18', '2019-07-19', '2019-07-20',
       '2019-07-21', '2019-07-22', '2019-07-23', '2019-07-24',
       '2019-07-25', '2019-07-26', '2019-07-27', '2019-07-28',
       '2019-07-29', '2019-07-30', '2019-07-31'], dtype='datetime64[D]')

## 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
# 原地计算，不能拷贝
a = np.ones(6, dtype=int).reshape(2,3)
b = np.ones(6, dtype=int).reshape(2,3)*2
b = a + b
a = (-a)/2
a * b

array([[-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5]])

## 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [38]:
# 去数组的整数部分
data = np.random.uniform(0,10,10)
print('data: \n', data)
print(u'方法一: ', data-data%1)
print(u'方法二: ', np.ceil(data)-1)
print(u'方法三: ', np.floor(data))
print(u'方法四: ', np.trunc(data))
print(u'方法五: ', data.astype(int))

data: 
 [9.97368926 5.74191901 2.91396922 9.39976421 9.31091324 6.46012322
 0.22093062 2.97036221 2.1799275  3.6473562 ]
方法一:  [9. 5. 2. 9. 9. 6. 0. 2. 2. 3.]
方法二:  [9. 5. 2. 9. 9. 6. 0. 2. 2. 3.]
方法三:  [9. 5. 2. 9. 9. 6. 0. 2. 2. 3.]
方法四:  [9. 5. 2. 9. 9. 6. 0. 2. 2. 3.]
方法五:  [9 5 2 9 9 6 0 2 2 3]


## 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
data = np.zeros((5,5), dtype=int)
data += np.arange(5)
print(u'方法一: \n', data)

data = np.tile(np.arange(5, dtype=int), [5,1])
print(u'方法二: \n', data)

方法一: 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
方法二: 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generate():
    for i in range(10):
        yield i
data = np.fromiter(generate(), dtype=float, count=-1)    
print('data: \n', data)

data: 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
data1 = np.linspace(0,1,11,endpoint=False)[1:]
data1

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

## 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
data = np.random.random(10)
print('data: \n', data)
data.sort()
print('after sort: \n', data)

data: 
 [0.11416586 0.70436296 0.93700989 0.40847326 0.50255451 0.97473493
 0.82740729 0.40148117 0.23778905 0.0058433 ]
after sort: 
 [0.0058433  0.11416586 0.23778905 0.40148117 0.40847326 0.50255451
 0.70436296 0.82740729 0.93700989 0.97473493]


## 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
# 使用reduce会很快，归并求和。
data = np.arange(100000)
%time print('np.sum: ', np.sum(data))
%time print('np.add.reduce: ', np.add.reduce(data))

np.sum:  4999950000
CPU times: user 289 µs, sys: 16 µs, total: 305 µs
Wall time: 313 µs
np.add.reduce:  4999950000
CPU times: user 211 µs, sys: 22 µs, total: 233 µs
Wall time: 241 µs


## 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
# 两个数组相等
a = np.array([1,2,3])
b = np.array([1,2,3])
print(u'方法一(没有发现不一样): ', False in np.equal(a, b))
print(u'方法二: ', np.array_equal(a, b))

# 两个数组不相等
a = np.array([1,2,3])
b = np.array([1,2,4])
print(u'方法一(发现了不一样): ', False in np.equal(a, b))
print(u'方法二: ', np.array_equal(a, b))

方法一(没有发现不一样):  False
方法二:  True
方法一(发现了不一样):  True
方法二:  False


## 43. Make an array immutable (read-only) (★★☆)

In [45]:
# 创建只读数组
data = np.zeros(10)
data.flags.writeable = False

## 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.97836616 0.4892738  0.83874701 0.4814912  0.44491497 0.27320879
 0.15478724 0.77925223 0.770219   1.03390994]
[1.21729922 1.4240938  0.0233511  0.54816871 1.39906292 0.17994245
 0.46826639 0.14667186 1.18672027 0.88319221]


## 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
# 创建大小为10的随机向量，并将最大值替换为0
data = np.random.random(10)
print('data: \n', data)
data[data.argmax()]=0
print('data: \n', data)

data: 
 [0.01709332 0.71471702 0.99647095 0.5526393  0.36257074 0.25243554
 0.40138695 0.1658376  0.510405   0.81319749]
data: 
 [0.01709332 0.71471702 0.         0.5526393  0.36257074 0.25243554
 0.40138695 0.1658376  0.510405   0.81319749]


## 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
# 创建一个带有x,y坐标的结构化数组
data = np.zeros((5,5), dtype=[('x', float), ('y', float)])
# meshgrid
data['x'], data['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print('data: \n', data)

data: 
 [[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [49]:
data1 = np.arange(10)
data2 = data1 * 5
print('data1: ', data1)
print('data2: ', data2)

result = 1 / (data1 - data2)
print('result: \n', result)

data1:  [0 1 2 3 4 5 6 7 8 9]
data2:  [ 0  5 10 15 20 25 30 35 40 45]
result: 
 [        inf -0.25       -0.125      -0.08333333 -0.0625     -0.05
 -0.04166667 -0.03571429 -0.03125    -0.02777778]


/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


## 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


## 49. How to print all the values of an array? (★★☆)

In [51]:
data = np.arange(100)
# set_printoptions设置打印的属性。threshold代表元素超过多少后，缩略打印
np.set_printoptions(threshold=np.inf)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
# 找到给定标量最接近的值
data = np.random.random(100)
print('data: \n', data)
# print('result: ', )
scalar = 0.2
data[(np.abs(data-scalar)).argmin()]

data: 
 [0.03971564 0.00505722 0.74041401 0.10405039 0.17594384 0.28738039
 0.99061223 0.32590517 0.28071973 0.85800114 0.64368367 0.49749336
 0.50481661 0.25083871 0.78574333 0.34377119 0.11942158 0.05107584
 0.39309423 0.61861154 0.85003957 0.17800434 0.6364773  0.27242111
 0.77892795 0.88701025 0.72226071 0.43824224 0.67104271 0.43550794
 0.61243921 0.07205382 0.2823447  0.3269881  0.35765801 0.92437432
 0.79956858 0.01400034 0.06667144 0.3567516  0.17005934 0.50696085
 0.97508601 0.16204578 0.41117213 0.83445832 0.28571007 0.99857839
 0.33193663 0.19331396 0.97809555 0.24825536 0.0075822  0.52113912
 0.87495162 0.25478842 0.64366192 0.65041881 0.54963476 0.41808305
 0.95740381 0.72971122 0.73358479 0.55992721 0.30259379 0.05561937
 0.53112904 0.55827417 0.8549501  0.35145958 0.96341052 0.50558123
 0.99408198 0.12291545 0.92648709 0.87176153 0.98645335 0.87133424
 0.00969957 0.25931781 0.52965046 0.18323373 0.7084219  0.92092322
 0.19732586 0.12119917 0.90160201 0.42104723 0.3673913

0.19732586365193583