## numpy 简述
Numpy(Numeric Python)提高了许多高级的数值编程工具，如：矩阵数据类型、矢量处理、以及精密的运算库。

1. python内置的list是无类型的；
2. 如需使用有类型的数组可以使用array.array；
3. numpy里有array更高效。

参考
- [Numpy简易入门](https://mp.weixin.qq.com/s/66SLsOBhUMP7qEuPE-BUnw)
- [Numpy练习题100题](https://github.com/rougier/numpy-100)


In [3]:
import numpy as np

In [2]:
array = np.array(np.arange(10))
print('array: ', array)
print('array type: ', type(array))
print('array dtype: ', array.dtype)
print('array ndim: ', array.ndim) # 维度
print('array size: ', array.size) # 数组元素的个数
print('array shape: ', array.shape)
print('array reshape[5, 2]: \n', array.reshape(2, 5))

array:  [0 1 2 3 4 5 6 7 8 9]
array type:  <class 'numpy.ndarray'>
array dtype:  int64
array ndim:  1
array size:  10
array shape:  (10,)
array reshape[5, 2]: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## 创建Numpy数组
### 创建一维数组

In [3]:
a = np.array([2,23,4,6,8,7], dtype=np.int32)  # 数据初始化array,可声明dtype的类型，常用int,float
a

array([ 2, 23,  4,  6,  8,  7], dtype=int32)

### 创建二维数组(矩阵)

In [4]:
aa = np.array([[2,23,4], [3,4,5]])
aa

array([[ 2, 23,  4],
       [ 3,  4,  5]])

In [5]:
# 将一维数组改成二维数组。2*3=6，如果数量不等于6就会报错。
a.reshape(2, 3)

array([[ 2, 23,  4],
       [ 6,  8,  7]], dtype=int32)

### 创建特定数组

In [6]:
# 生成连续数值数组,这里支持浮点类型(左闭右开)。而python里不支持浮点.
# 起始点，终点，步长
np.arange(0, 10, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [7]:
# 和arrage类似，只是这里不是设置步长。
# 起始点，终点，分割份数；包括终点
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [8]:
# 创建全0的数组
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# 创建全1的数组
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# 创建全空数组，里面的值接近于零
np.empty((2,5))

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.]])

In [11]:
# 3*5的矩阵填充666
np.full((3,5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [12]:
# 以2为底，指数为1,2...,10
np.logspace(1,10,10, base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [13]:
# 创建对角数组
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
# 主对角线偏移1的数组
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

### 随机数

In [15]:
# 整数随机
np.random.randint(0,10, size=20)

array([3, 1, 9, 5, 6, 4, 0, 3, 1, 9, 7, 8, 0, 8, 1, 1, 1, 1, 1, 7])

In [16]:
# 0-1的随机数
np.random.random((2,5))

array([[0.31578505, 0.56741963, 0.99593398, 0.53085863, 0.65105491],
       [0.13986837, 0.77489267, 0.04507101, 0.59637248, 0.71395766]])

In [17]:
# 正态分布
np.random.normal(0,1,20)

array([ 1.00296476, -0.63799176,  0.28187091,  0.61422251, -0.31410789,
        0.81096094, -0.845968  ,  0.36040958,  0.74374277,  1.28427408,
       -0.71169611,  0.01389769, -1.3797891 , -0.10498537, -0.31589003,
        0.60017846, -0.83360094, -0.47233327, -1.09834707,  0.21010578])

In [18]:
# 5~10的数随机浮点数
np.random.uniform(5, 10, size=(3,5))

array([[7.61797381, 8.19180863, 9.69134351, 8.65022415, 6.13583421],
       [9.07230902, 9.33861371, 9.95472495, 7.82668697, 6.44112929],
       [8.21394282, 8.2244378 , 8.64578818, 9.04335296, 7.88647697]])

In [19]:
# 伪随机数(计算机里都是伪随机数)
np.random.seed(0) # 随机种子
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

## 改变数组

### repeat
实现某一维上的元素复制操作

In [20]:
a = np.array([[1,2],[3,4]])

In [21]:
# 在维度0上复制元素2次
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [22]:
# 在维度1上复制元素2次
np.repeat(a, 2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

### tile函数
找到矩阵的最小单位，然后title使用最小单位组织成目标矩阵。

In [23]:
# 一维：将[0,1]横向复制5次
np.tile([0,1], 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [24]:
# 二维：构建8*8棋盘。棋盘的最小单位是2*2矩阵[[1,0],[0,1]]，将其复制按照行和列分别复制4次即可(1代表黑格，0代表白格)
np.tile([[1,0],[0,1]], [4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### flatten函数
改变shape，将高维数组拍成向量。但是，它会发生数组复制行为

In [25]:
v1 = np.random.randint(1,10,(2,3))
v1

array([[2, 7, 8],
       [8, 9, 2]])

In [26]:
# 法一
v2 = v1.flatten()
v2

array([2, 7, 8, 8, 9, 2])

In [27]:
# 法二
v1.reshape(1,6)

array([[2, 7, 8, 8, 9, 2]])

### vstack
沿竖直方向合并多个数组

In [28]:
# 法一
a = np.array([[1,2],[3,4]])
b = np.array([[4,5]])
np.vstack([a, b])


array([[1, 2],
       [3, 4],
       [4, 5]])

In [29]:
# 法二
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [4, 5]])

### hstack

In [30]:
# 法一
a = np.array([[1,2],[3,4]])
b = np.array([[6,7], [8,9]])
np.hstack([a, b])


array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

In [31]:
# 法二
np.concatenate((a,b),axis=1)

array([[1, 2, 6, 7],
       [3, 4, 8, 9]])

## 数据类型与转化

In [4]:
data = np.array([[1,2,3],[4,5,6]])
data.dtype

dtype('int64')

In [5]:
data.astype('float64').dtype

dtype('float64')

In [6]:
data.astype(np.float64, copy=False).dtype

dtype('float64')

## 索引和切片
### 普通索引与切片

In [35]:
# 一维数组索引
data = np.arange(10)
print(u'一维数组******')
print(u'data: ', data)
print(u'索引2对应的元素: ', data[2])
print(u'索引2~5对应的元素: ', data[2:5])
print(u'索引2~8,步长为2对应的元素: ', data[2:8:2])

# 二维数组索引
data = np.arange(25).reshape(5,5)
print(u'\n二维数组******')
print(u'data: \n', data)
print(u'data[2,1]: ', data[2,1])
print(u'data[2:]: \n', data[2:])
print(u'data[2,:]: \n', data[2,:])
print(u'data[2][0:3]: \n', data[2][0:3])

一维数组******
data:  [0 1 2 3 4 5 6 7 8 9]
索引2对应的元素:  2
索引2~5对应的元素:  [2 3 4]
索引2~8,步长为2对应的元素:  [2 4 6]

二维数组******
data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,1]:  11
data[2:]: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[2,:]: 
 [10 11 12 13 14]
data[2][0:3]: 
 [10 11 12]


### 花式索引

In [36]:
data = np.arange(25).reshape(5,5)
# 设置数组是只读
data.flags.writeable = False
print(u'data: \n', data)
print(u'data[[0,2]]: \n', data[[0,2]])  # 第0,2行
print(u'data[:][1]: \n', data[[1],[1]]) # 第1行第1列

data: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
data[[0,2]]: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]
data[:][1]: 
 [6]


### 布尔型
支持布尔型按照条件筛选

In [37]:
data = np.arange(1, 26).reshape(5,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
# 筛选15~20之间的数据
data[(data>=15) & (data<=20)]

array([15, 16, 17, 18, 19, 20])

### 查找第n个元素对应的位置

In [39]:
# 查找6*7*8的数组，第100个元素对应的位置，默认是按行查找
np.unravel_index(100, (6,7,8), order='C')

(1, 5, 4)

In [40]:
# 按照列查找
np.unravel_index(100, (6,7,8), order='F')

(4, 2, 2)

## 合并与分割

### 合并

In [41]:
# 一维数组合并
data1 = np.array([0,1,2,3,4])
data2 = np.array([5,6,7,8,9])
np.concatenate([data1, data2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# 二维数组合并 numpy.concatenate((a1, a2, ...), axis=0, out=None).axis=0为行，axis=1为列。
data1 = np.arange(0,6).reshape(2,3)
data2 = np.arange(10,16).reshape(2,3)

np.concatenate([data1, data2], axis=0)
np.concatenate([data1, data2], axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

## 分割

In [43]:
data = np.arange(0,25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
# 按行分割
upper, lower = np.vsplit(data, [2])
print('upper: \n', upper)
print('lower: \n', lower)

upper: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
lower: 
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [45]:
# 按列分割
left, right = np.hsplit(data, [2])
print('left: \n', left)
print('right: \n', right)

left: 
 [[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]
right: 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


## 其他

### 逆序

In [46]:
data = np.arange(10)
reverse_data = data[::-1]
print('data: \n', data)
print('reverse_data: \n', reverse_data)

data: 
 [0 1 2 3 4 5 6 7 8 9]
reverse_data: 
 [9 8 7 6 5 4 3 2 1 0]


### 排序

### 转置

### 对角线

In [47]:
data = np.arange(9).reshape(3,3)
print('data: \n', data)

print(u'对角线 \n', np.diag(data))
print(u'对角线之上1个单位的元素 \n', np.diag(data, k=1))
print(u'对角线之下1个单位的元素 \n', np.diag(data, k=-1))

data: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
对角线 
 [0 4 8]
对角线之上1个单位的元素 
 [1 5]
对角线之下1个单位的元素 
 [3 7]


## 多种取整方式

In [48]:
data = np.random.uniform(-10,10,10)
print('data: \n', data)
print(u'截取整数部分: ', np.trunc(data))
print(u'向上取整: ', np.ceil(data))
print(u'向下取整: ', np.floor(data))
print(u'四舍五入取整: ', np.rint(data))

data: 
 [ 8.51193277 -8.57927884 -8.25741401 -9.59563205  6.65239691  5.56313502
  7.40024296  9.57236684  5.98317128 -0.77041275]
截取整数部分:  [ 8. -8. -8. -9.  6.  5.  7.  9.  5. -0.]
向上取整:  [ 9. -8. -8. -9.  7.  6.  8. 10.  6. -0.]
向下取整:  [  8.  -9.  -9. -10.   6.   5.   7.   9.   5.  -1.]
四舍五入取整:  [  9.  -9.  -8. -10.   7.   6.   7.  10.   6.  -1.]
