- 题目来源于：https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_no_solution.ipynb
- 参考：https://www.jianshu.com/p/385d47d03cfb

In [1]:
import numpy as np

## 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [2]:
# TODO: 不太理解
np.zeros(10, [
    ('position', [('x', float, 1), ('y', float, 1)]),
    ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)])
])


/Users/cleland/.pyenv/versions/3.7.1/envs/base/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

## 52.Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
TODO: 未理解

## 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [3]:
data = np.full((2,5), 1.25)
data

array([[1.25, 1.25, 1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25, 1.25, 1.25]])

In [4]:
# float32转化为int32
data[:, 1] = data[:, 1].astype(np.int32, copy=False)
data

array([[1.25, 1.  , 1.25, 1.25, 1.25],
       [1.25, 1.  , 1.25, 1.25, 1.25]])

## 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11
```

In [5]:
from io import StringIO

s = StringIO("""
1, 2, 3, 4, 5
6,  ,  , 7, 8
,  , 9,10,11
""")

np.genfromtxt(s, delimiter=",", dtype=np.int)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

## 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
TODO: 未理解题意

## 56. Generate a generic 2D Gaussian-like array (★★☆)
TODO: 未掌握

## 57. How to randomly place p elements in a 2D array? (★★☆)

In [6]:
data = np.zeros((10,10), dtype=np.int)
np.put(data, np.random.choice(range(10*10), 5, replace=False), 1)         
print(data)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


## 58. Subtract the mean of each row of a matrix (★★☆)

In [7]:
data = np.random.rand(5, 10)
data.mean(axis=1, keepdims=True)

array([[0.46655877],
       [0.45675351],
       [0.46544548],
       [0.65327899],
       [0.48234642]])

In [8]:
np.array([0.46504886, 0.00649566, 0.92594331, 0.74587118, 0.36715231,
        0.65933688, 0.87891355, 0.04615191, 0.21711916, 0.84124967]).mean()

0.515328249

## 59. How to sort an array by the nth column? (★★☆)

In [13]:
data = np.random.randint(0, 50, (5,5))
data

array([[14, 33,  0, 33, 38],
       [21,  1,  6, 40, 48],
       [ 7, 23, 30, 41, 19],
       [ 5, 44, 40, 25, 25],
       [25, 37,  9, 42, 13]])

In [16]:
# 按照第3列排序
data[data[:, 2].argsort()]

array([[14, 33,  0, 33, 38],
       [21,  1,  6, 40, 48],
       [25, 37,  9, 42, 13],
       [ 7, 23, 30, 41, 19],
       [ 5, 44, 40, 25, 25]])

## 60. How to tell if a given 2D array has null columns? (★★☆)

In [38]:
data = np.array([1,2,np.nan,9,11,np.nan]).reshape(2,3)
data

array([[ 1,  2,  5],
       [ 9, 11, 20]])

In [39]:
# data
print((~data.any(axis=0)).any())

False


## 61. Find the nearest value from a given value in an array (★★☆)

In [45]:
data = np.random.uniform(0,1,10)
data.sort()
data

array([0.08129102, 0.14633019, 0.21601972, 0.5488707 , 0.61478341,
       0.69209046, 0.69447986, 0.78571119, 0.80137654, 0.90003909])

In [42]:
find_value = 0.5 
data[np.abs(data-find_value).argmin()]

0.584516782591417

## 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
TODO: 进一步了解

In [47]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(f'A:\n {A}')
print(f'B:\n {B}')

A:
 [[0]
 [1]
 [2]]
B:
 [[0 1 2]]


In [48]:
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 63. Create an array class that has a name attribute (★★☆)

TODO: 需进一步了解

In [57]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")


range_10


In [58]:
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10
