In [1]:
import numpy as np

## 查看版本信息

In [2]:
print(u'numpy 版本', np.__version__)
print(u'numpy 配置: \n', np.show_config()) 

numpy 版本 1.17.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
numpy 配置: 
 None


## python内置list vs numpy

可以看出不管在内存消耗，还是计算上。numpy更优。原因：
- python的list是个通用的结果。他能包含任意类型的对象，并且是动态类型
- numpy的ndarry是静态的，同质的类型

In [22]:
from pympler.asizeof import asizeof
# 将(1~1000000) 放大一倍

# python内置list
print('python内置list')
list1 = range(1, 1000000)
%time list1 = [item * 2 for item in list1]
print(asizeof(list1)/(1024*1024), ' MB')

# numpy
print('\nnumpy')
nlist1 = np.arange(1,1000000)
%time nlist1 = nlist1 * 2
print(asizeof(nlist1)/(1024*1024), ' MB')


python内置list
CPU times: user 84.6 ms, sys: 20.8 ms, total: 105 ms
Wall time: 116 ms
38.812095642089844  MB

numpy
CPU times: user 2.03 ms, sys: 2.84 ms, total: 4.86 ms
Wall time: 4.91 ms
7.629478454589844  MB


In [15]:
import sys
from pympler.asizeof import asizeof

tuple1 = ('1234','2019-04-27','23.4658')
tuple2 = ('1563','2019-04-27','19.2468')
klist1 = [tuple1]
klist2 = [tuple1,tuple2]
# The results for the following did not answer my question 
print ("sys.getsizeof(klist1): ",sys.getsizeof(klist1))
print ("sys.getsizeof(klist2): ",sys.getsizeof(klist2))    
# The results for the following give a quite reasonable answer
print ("asizeof(klist1): ",asizeof(klist1))
print ("asizeof(klist2): ",asizeof(klist2))

sys.getsizeof(klist1):  72
sys.getsizeof(klist2):  80
asizeof(klist1):  320
asizeof(klist2):  576


## 数组内存占用

In [4]:
# 计算数组所在内存大小
data = np.arange(50000000)
%time print(u'数组所在内存大小(方法一): ', data.size*data.itemsize)
%time print(u'数组所在内存大小(方法二): ', data.nbytes)
# 也可以使用python内置的方法，不过效率估计会低一些
from sys import getsizeof
%time print(u'数组所在内存大小(方法三): ', getsizeof(data))

数组所在内存大小(方法一):  400000000
CPU times: user 104 µs, sys: 74 µs, total: 178 µs
Wall time: 183 µs
数组所在内存大小(方法二):  400000000
CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 38.9 µs
数组所在内存大小(方法三):  400000096
CPU times: user 40 µs, sys: 12 µs, total: 52 µs
Wall time: 50.3 µs


## 查看命令行帮助文档

In [5]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [6]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

## 打印设置

### threshold 最大打印数

超过后，缩略打印。默认值100

In [7]:
data = np.arange(100)
print('data: \n', data)
# set_printoptions设置打印的属性。threshold代表元素超过多少后，缩略打印. 默认值1000
np.set_printoptions(threshold=10)
print('data: \n', data)
# 放开threshold，打印全部，不管数组多大
np.set_printoptions(threshold=np.inf)
print('data: \n', data)

data: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
data: 
 [ 0  1  2 ... 97 98 99]
data: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


### precision 小数保留的位数
小数保留的位数

In [8]:
data = np.random.random(10)
print('data: \n', data)
np.set_printoptions(precision=2)
print('data: \n', data)

data: 
 [0.08191189 0.60000345 0.92971769 0.79710831 0.35720261 0.12690531
 0.66931877 0.22506644 0.85528685 0.83947446]
data: 
 [0.08 0.6  0.93 0.8  0.36 0.13 0.67 0.23 0.86 0.84]


### 忽略警告

In [9]:
default = np.seterr(all='ignore')
np.ones(1) / 0

array([inf])