In [2]:
import numpy as np

## 数组运算
- 标量(Scalar): 只有大小，没有法相的量。如1，2，3等。
- 向量(Vector): 也叫矢量，有大小和方向的量，其实就是一串数字，如(1,2)
- 矩阵(Matrix): 好几个向量拍成一排合并成的一堆数字
- 张量(Tensor): 按照任意维排列的一堆数字的推广。标量是零维张量，向量是一维张量，矩阵是二维张量

### 数组与标量之间的运算

In [59]:
data = np.arange(10).reshape(2,5)
print('data: \n', data)

print('data+2: \n', data+2)
print('data-2: \n', data-2)
print('data*2: \n', data*2)
print('data/2: \n', data/2)
print('data**2: \n', data**2)
print('data//2: \n', data//2)
print('data%2: \n', data%2)

data: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
data+2: 
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
data-2: 
 [[-2 -1  0  1  2]
 [ 3  4  5  6  7]]
data*2: 
 [[ 0  2  4  6  8]
 [10 12 14 16 18]]
data/2: 
 [[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]]
data**2: 
 [[ 0  1  4  9 16]
 [25 36 49 64 81]]
data//2: 
 [[0 0 1 1 2]
 [2 3 3 4 4]]
data%2: 
 [[0 1 0 1 0]
 [1 0 1 0 1]]


### 向量化运算

In [4]:
data1 = np.arange(10).reshape(2, 5)
data2 = np.arange(10).reshape(2, 5)
print('data1: \n', data1)
print('data2: \n', data2)

print('data1+data2: \n', data1+data2)
print('data1-data2: \n', data1-data2)
print('data1*data2: \n', data1*data2)
print('data1/data2: \n', data1/data2)

# 矩阵data1转置
print('data1.T: \n', data1.T)

data1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
data2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
data1+data2: 
 [[ 0  2  4  6  8]
 [10 12 14 16 18]]
data1-data2: 
 [[0 0 0 0 0]
 [0 0 0 0 0]]
data1*data2: 
 [[ 0  1  4  9 16]
 [25 36 49 64 81]]
data1/data2: 
 [[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
data1.T: 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


In [9]:
# 矩阵的积
data1 = np.arange(10)
data2 = data1[::-1]

print('data1: ', data1)
print('data2: ', data2)
print('dot: ', np.dot(data1, data2))

data1:  [0 1 2 3 4 5 6 7 8 9]
data2:  [9 8 7 6 5 4 3 2 1 0]
dot:  120


### 数组广播
TODO: 待补充

## 常用函数

In [28]:
data1 = np.array([1,4,9,16,25,36]).reshape(2,3)
print('data1: \n', data1)
print('sqrt: \n', np.sqrt(data1)) # 开方
print('abs: \n', np.abs(data1)) # 绝对值
print('square: \n', np.square(data1)) # 求平方

data2 = np.array([1,2,3,4,5,6]).reshape(2,3)
print('data2: \n', data2)
print('data1+data2: \n', np.add(data1, data2)) # 两个矩阵相加
print('data1*data2: \n', np.multiply(data1, data2)) # 两个矩阵相乘
print('greater: \n', np.greater(data1, data2)) # 元素比较

data1: 
 [[ 1  4  9]
 [16 25 36]]
sqrt: 
 [[1. 2. 3.]
 [4. 5. 6.]]
abs: 
 [[ 1  4  9]
 [16 25 36]]
square: 
 [[   1   16   81]
 [ 256  625 1296]]
data2: 
 [[1 2 3]
 [4 5 6]]
data1+data2: 
 [[ 2  6 12]
 [20 30 42]]
data1*data2: 
 [[  1   8  27]
 [ 64 125 216]]
greater: 
 [[False  True  True]
 [ True  True  True]]


## 数据统计

### 单维度聚合

In [62]:
data = np.arange(2, 20)
print('data: \n', data)

print('sum: ', data.sum())
print('mean: ', data.mean())
print('min: ', data.min())
print('max: ', data.max())
print('argmin: ', data.argmin())
print('argmax: ', data.argmax())
print('cumsum: ', data.cumsum()) # 元素累加
print('cumprod: ', data.cumprod()) # 元素累计积

data: 
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
sum:  189
mean:  10.5
min:  2
max:  19
argmin:  0
argmax:  17
cumsum:  [  2   5   9  14  20  27  35  44  54  65  77  90 104 119 135 152 170 189]
cumprod:  [                 2                  6                 24
                120                720               5040
              40320             362880            3628800
           39916800          479001600         6227020800
        87178291200      1307674368000     20922789888000
    355687428096000   6402373705728000 121645100408832000]


### 多维度聚合

In [66]:
data = np.arange(0,25).reshape(5,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
print(u'全部元素求和', data.sum())
print(u'按行横穿求和', data.sum(axis=0))
print(u'按列横穿求和', data.sum(axis=1))

全部元素求和 300
按行横穿求和 [50 55 60 65 70]
按列横穿求和 [ 10  35  60  85 110]


## 随机数

In [48]:
# 整数随机
np.random.randint(0,10, size=20)

array([3, 3, 3, 7, 0, 1, 9, 9, 0, 4, 7, 3, 2, 7, 2, 0, 0, 4, 5, 5])

In [51]:
# 0-1的随机数
np.random.random((2,5))

array([[0.61209572, 0.616934  , 0.94374808, 0.6818203 , 0.3595079 ],
       [0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787]])

In [54]:
# 正态分布
np.random.normal(0,1,20)

array([ 1.03081595, -1.27698899,  0.83771977, -1.49011141, -1.070215  ,
       -0.20912862,  0.60457228, -1.74305823,  1.52422681,  1.86357532,
        1.29137792,  1.30069627,  0.91820283, -0.15880047, -0.96406336,
       -1.99077882,  0.08973073,  0.11485388, -0.58581518,  0.29877204])

In [52]:
# 伪随机数(计算机里都是伪随机数)
np.random.seed(0) # 随机种子
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])