In [7]:
import numpy as np

## Day29练习题

### 创建一个[3,5]所有元素为True的数组

In [9]:
# 法1
np.full((3,5), True)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [11]:
# 法二
np.ones((3,5), dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### 一维数组转二维

In [13]:
data = np.arange(1,26)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [14]:
# 一维转二维
data.reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 数组所有奇数替换为-1

In [16]:
data = np.arange(0,50)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [17]:
# 奇数替换为-1
data[data%2!=0] = -1
data

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1,
       34, -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1])

### 2个numpy数组的差集与交集

In [18]:
m, n = np.arange(20), np.arange(1, 30, 3)

In [24]:
# 交集
np.intersect1d(m, n)

array([ 1,  4,  7, 10, 13, 16, 19])

In [23]:
# 差集
np.setdiff1d(m, n)

array([ 0,  2,  3,  5,  6,  8,  9, 11, 12, 14, 15, 17, 18])

### 筛选出指定前的所有元素

In [28]:
data = np.arange(0,101, 2)
data

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [29]:
# 筛选出50~60
data[(data>=50) & (data<=60)]

array([50, 52, 54, 56, 58, 60])

### 二维数组交换两列
使用的是花式索引

In [35]:
data = np.arange(1,11,1).reshape(2,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
# 交换第0,1列
data[:, [1,0,2,3,4]]

array([[ 2,  1,  3,  4,  5],
       [ 7,  6,  8,  9, 10]])

### 二维数组行翻转

In [38]:
data = np.arange(1,11,1).reshape(2,5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
# 行上翻转
data[::-1]

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### 生成数组5~10、shape为(3,5)的随机浮点数

In [43]:
np.random.uniform(5, 10, size=(3,5))

array([[7.16920376, 8.28715401, 8.5910241 , 8.54178112, 7.9632954 ],
       [9.0329778 , 7.84255094, 8.66893366, 6.78414955, 7.95137975],
       [5.55290391, 9.83983944, 5.9398377 , 6.49584484, 7.05574639]])